### ISSUE TITLE
how to send multiple notifications of the same type for the same user

### ISSUE THREAD

**Issue by mekki91anisaa** [machour/yii2-notifications#50]
Hello,
I want to send a multiple notifications from different users to one only admin user
but I can't add multiple notifications for the same user
Notification::notify (Notification :: KEY_NEW_MESSAGE, $admin_user, "hello");
Please can you telle me what I do??

Have good day

**Comment by machour** [comment]
I thin you could dynamically generate the key
(Notification::KEY_NEW_MESSAGE . '-' . $user_id)

On Jan 5, 2018 10:00, "mekki91anisaa" <notifications@github.com> wrote:

Hello,
I want to send a multiple notifications from different users to one only
admin user
but I can't add multiple notifications for the same user
Notification::notify (Notification :: KEY_NEW_MESSAGE, $admin_user,
"hello");
Please can you telle me what I do??

Have good day

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/machour/yii2-notifications/issues/50>, or mute the
thread

**Comment by mekki91anisaa** [comment]
When I changed for this (Notification::KEY_NEW_MESSAGE . '-' . $user_id) I
have Exception(in screenshot).
why does it register a single user_id in database, do you do a check
somewhere????

2018-01-05 10:31 GMT+01:00 Mehdi Achour <notifications@github.com>:

> I thin you could dynamically generate the key
> (Notification::KEY_NEW_MESSAGE . '-' . $user_id)
>

**Comment by mekki91anisaa** [comment]
you can answer me please,????

**Comment by machour** [comment]
@mekki91anisaa you didn't provide the screenshot you're mentioning.

I don't really have the time to provide support these days, but I'll do my best. Meanwhile, don't hesitate to dive into the code, it's pretty small :)

**Comment by mekki91anisaa** [comment]
thank you very much for your response,I solved it :)
and thank you for this plugin is really useful

2018-01-09 11:58 GMT+01:00 Mehdi Achour <notifications@github.com>:
